### ISSUE TITLE
Anki 2.1.23: Type error when calling AnkiWebView.stdHtml

### ISSUE THREAD

**Issue by arueckle** [trevorld/Hanzi_Stats#15]
In Anki 2.1.23, Hanzi Stats throws the following error when clicking on the menu item Tools->Hanzi Stats:

> Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
> Platform: Mac 10.15.4
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-05-01 16:11:22
> Add-ons possibly involved: ⁨Hanzi Stats⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "~/Library/Application Support/Anki2/addons21/181243826/__init__.py", line 265, in onhanziStats
>     w.stdHtml(rep, css)
>   File "aqt/webview.py", line 335, in stdHtml
> TypeError: can only concatenate list (not "str") to list

I was able to fix it locally by changing line 265 in __init.py from
`w.stdHtml(rep, css)`
to
`w.stdHtml(rep, [css])`

It is unclear to me, though, if this would introduce any backward incompatibilities.

**Comment by trevorld** [comment]
Thanks for the bug report!

Both forms seem to work without error in Anki 2.1.15 so I'm not sure if we need to be conservative and use a definitely backwards-compatible try-except block:
```
try:
    w.stdHtml(rep, css)
except TypeError:
    w.stdHtml(rep, [css,])
```

I'll maybe see if I can get an older version of Anki 2 running as well as the latest version of Anki 2.

**Comment by trevorld** [comment]
Downloaded Anki 2.1.0 and 2.1.25.  Change seems to work with both versions so I won't go with the conservative version.  I've uploaded an updated version of Hanzi_Stats to ankiweb.
