### ISSUE TITLE
Latest Version Not Accurate

### ISSUE THREAD

**Issue by npschweizer** [trevorld/Hanzi_Stats#23]
Since upgrading to the latest version of anki (24.06.2), I've noticed that hanzi stats does not seem to be "seeing" all of the characters in my deck. For instance, according to hanzi stats I'm missing 泛

<img width="500" alt="image" src="https://github.com/user-attachments/assets/0ca17eab-2af6-464d-8333-f12468af044b">

However, I can find a card with this character in my deck 

<img width="602" alt="image" src="https://github.com/user-attachments/assets/72586d8f-e97b-4baf-92fd-bcb62f92c140">

Is this likely a compatibility issue with the latest anki version? Possibly an issue with my database? I tried running anki's "Check database" function and nothing changed so I'm not sure what to make of this.

**Comment by trevorld** [comment]
I don't notice any difference with my deck between anki 23.10.1 and anki 24.06.3. i.e. before and after I see the same number of seen characters.  How far back do you have to go before you see a difference?

Note that Hanzi Stats doesn't "see" suspended cards or new cards that haven't ever been studied so the example you gave me is an example that "should" be "missing".  I don't think this should be new behavior but perhaps you recently have had several cards get suspended?  Note this is a good thing if before you were making the mistake of not letting "leeches" go suspended...

**Comment by npschweizer** [comment]
I think suspension was the issue - I tried toggling suspension and hanzi stats "sees" it again.

Thanks for your help and the great add on!
