### ISSUE TITLE
Anki 2.1

### ISSUE THREAD

**Issue by Hansll** [trevorld/Hanzi_Stats#5]
Hello,

first of all thank you for that amazing addon.
Any chance that you release your addon for Anki 2.1 as well?
Would be amazing to see it in the new version.

Thank you very much for your work!

**Comment by trevorld** [comment]
Probably but it might take a while if the changes will be non-trivial, I won't have a lot of free time over the next few months.

Note to self: https://apps.ankiweb.net/docs/addons21.html

**Comment by trevorld** [comment]
Latest Anki beta seems pretty unstable (seg faulted on me twice in a couple minute stretch while reviewing my cards without me even having attempted to install any plugins).  Will wait until the beta is more stable before finishing porting over plugin.

**Comment by trevorld** [comment]
I've got the plugin working in 2.1 and have uploaded it the Anki addons manager.  It behaves a little bit differently but everything important should now work.

Turns out I needed to set a certain environmental variable before launching the beta version of Anki...
