### ISSUE TITLE
Anki 2.1 - Not showing any stats

### ISSUE THREAD

**Issue by aNerdgirl** [trevorld/Hanzi_Stats#9]
First of all, thank you very much for this great addon.
Unfortunately I can't figure out how to make it work.

Whatever field I use ("1", "all", ...) I never get any stats, it always shows 0 words.
What am I doing wrong?
![2018-10-01 08_32_54-configuration](https://user-images.githubusercontent.com/41619287/46264998-10fe8900-c512-11e8-9996-95cc72a4ecc1.png)
![2018-10-01 08_33_49-anki](https://user-images.githubusercontent.com/41619287/46264999-11971f80-c512-11e8-9b03-ccc911cf9302.png)
![2018-10-01 08_34_07-browse 323 cards shown 1 selected](https://user-images.githubusercontent.com/41619287/46265000-11971f80-c512-11e8-8877-257dcd04a178.png)

**Comment by trevorld** [comment]
Not reproducible on my end with my deck (even after re-downloading Anki 2.1 and Hanzi Stats) and don't see anything obviously wrong with your deck (i.e. your sort field and 1st field are both Hanzi so the plugin by default should be seeing them without needing further configuration).

Could you export and give me (a subset of?) your Chinese Anki deck so I can see if I can reproduce the issue with your deck on my computer.  What OS are you using?  Have you tried using Anki 2.0 and the Anki 2.0 version of the plugin?

![browser](https://user-images.githubusercontent.com/2433259/46308408-69fc0a80-c56e-11e8-84c0-fd39c3ee9cb5.png)
![hanzi_stats](https://user-images.githubusercontent.com/2433259/46308410-6c5e6480-c56e-11e8-87cf-d7f15873ab59.png)

**Comment by aNerdgirl** [comment]
Very strange. I just installed Anki 2.0 (for testing purpose) and created a new deck (super basic one, front Hanzi, back english) and it is still not working.

I use Windows 10. Newest Anki 2.0 Version and newest Anki 2.1 beta Version (as well as the newest version of your addon; even tried deleting and re-installing it + restarting Anki of course).

By the way, not sure if that helps, I opended your Python files and used the simple search engine (to look up some HSK 1 words like "我，你，老师" and I can find them. So it shouldn't be some weird formatting or font problem.

Attached you can find my Anki 2.1 deck. Or at least a minimalistic version to test it yourself.

Big thank you for your time and help, by the way!
[collection-2018-10-02@09-59-29.zip](https://github.com/trevorld/Hanzi_Stats/files/2436225/collection-2018-10-02.09-59-29.zip)

**Comment by trevorld** [comment]
Your deck and the Hanzi Stats plugin (without configuration) seem to work on my native OS (Ubuntu LInux) as well as in a Windows 10 virtual machine.  Here is a screenshot of the plugin on my Windows 10 virtual machine after studying a few cards in the deck:

![image](https://user-images.githubusercontent.com/2433259/46504859-0da22080-c7e4-11e8-9776-f4b468b78fd5.png)

I assume after restoring the plugin to its defaults you have restarted both Anki and Windows 10?  You do have non-suspended **studied** cards in your decks, right?

**Comment by aNerdgirl** [comment]
I feel so stupid.
"sutdied" cards was the catch. I checked the plugin against a freshly unused deck (because I wanted to make sure, to not mess with anything). I am so sorry. It works perfectly!
Thank you very much for your time and work!
